export const PELDA_ACTION = 'PELDA_ACTION';
export const LOAD_MEME_FEED = 'LOAD_MEME_FEED';
export const LOAD_ACTUAL_MEME = 'LOAD_ACTUAL_MEME';
export const UNLOAD_ACTUAL_MEME = 'UNLOAD_ACTUAL_MEME';
